# -*- coding: utf-8 -*-
"""xgboost_lightgbm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ky4f3suvbBV6QVhW7jCbq6NUURsDamUo
"""

# importing libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

df = pd.read_csv("real_estate_listings_india_2025.csv")
print("Original Shape:", df.shape)

def convert_size(size):
    try:
        size = str(size).replace(" sqft", "").strip()
        if "-" in size:
            low, high = size.split("-")
            return (float(low) + float(high)) / 2
        else:
            return float(size)
    except:
        return np.nan

df["size_avg"] = df["size"].apply(convert_size)

# clean data

df.drop(columns=["url", "date", "size"], inplace=True, errors="ignore")
df.dropna(inplace=True)
print("Cleaned Shape:", df.shape)

# Log Transform Target

df["price"] = pd.to_numeric(df["price"], errors="coerce")
df = df[df["price"] > 0]
df["log_price"] = np.log(df["price"])

df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna(subset=["log_price"])

X = df.drop(columns=["price", "log_price"])
y = df["log_price"]

# Identify Categorical Columns

categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical:", categorical_cols)
print("Numeric:", numeric_cols)

# Preprocessing (One-Hot Encoding)

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ],
    remainder="passthrough"
)

# Define Models

xgb_model = XGBRegressor(
    n_estimators=150,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

lgbm_model = LGBMRegressor(
    n_estimators=150,
    max_depth=3,
    learning_rate=0.05,
    num_leaves=15,
    verbose=-1,
    random_state=42
)

# create pipeline

xgb_pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", xgb_model)
])

lgbm_pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", lgbm_model)
])

# cross validation

kf = KFold(n_splits=10, shuffle=True, random_state=42)
def evaluate_model(pipeline, X, y):
    mae_scores = []
    rmse_scores = []
    r2_scores = []

    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        pipeline.fit(X_train, y_train)
        preds = pipeline.predict(X_test)

        y_test_exp = np.exp(y_test)
        preds_exp = np.exp(preds)

        mae = mean_absolute_error(y_test_exp, preds_exp)
        rmse = np.sqrt(mean_squared_error(y_test_exp, preds_exp))
        r2 = r2_score(y_test_exp, preds_exp)

        mae_scores.append(mae)
        rmse_scores.append(rmse)
        r2_scores.append(r2)

    return {
        "MAE": np.mean(mae_scores),
        "RMSE": np.mean(rmse_scores),
        "R2": np.mean(r2_scores)
    }

print("Evaluating XGBoost...")
xgb_results = evaluate_model(xgb_pipeline, X, y)

print("Evaluating LightGBM...")
lgbm_results = evaluate_model(lgbm_pipeline, X, y)

# Train Final Model on Full Data

if xgb_results["MAE"] < lgbm_results["MAE"]:
    final_model = xgb_pipeline
    best_model_name = "XGBoost"
else:
    final_model = lgbm_pipeline
    best_model_name = "LightGBM"

print(f"Best Model Selected: {best_model_name}")

# User input example

new_data = pd.DataFrame({
    "beds": [2],
    "baths": [2],
    "size_avg": [1200],
    "city": ["Hyderabad"],
    "type": ["2 BHK Flat"],
    "neighborhood": ["Madhapur"]
})

log_pred = final_model.predict(new_data)
price_pred = np.exp(log_pred)

print("Predicted Price: ₹{:,.0f}".format(price_pred[0]))